name: Executar Auditoria de Marica Diario

on:
  schedule:
    - cron: '0 3 * * *' # Executa de forma automatica todos os dias as 03h00 da manha
  workflow_dispatch: # Permite que voce clique em um botao para rodar manualmente

jobs:
  rodar-ia:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissao para salvar a planilha no repositorio
    steps:
      - name: Baixar o codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar o ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar ferramentas necessarias
        run: pip install google-genai pandas requests beautifulsoup4

      - name: Executar o script do Auditor IA
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }} # Injeta o token guardado no segredo
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}   # Injeta o ID guardado no segredo
        run: python bot.py

      - name: Salvar planilha atualizada de volta no GitHub
        run: |
          git config --global user.name "Auditor Robot"
          git config --global user.email "bot@github.com"
          git add -A
          git commit -m "Planilha automatica atualizada [Automático]" || exit 0
          git push
