name: Executar Auditoria de Marica Diario

on:
  schedule:
    - cron: '0 3 * * *' # Executa de forma automatica todos os dias as 03h00 da manha
  workflow_dispatch: # Permite que voce clique em um botao para rodar manualmente

jobs:
  rodar-ia:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissao para salvar o arquivo de volta no repositorio
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Força o uso do Node24 e elimina o aviso amarelo
    steps:
      - name: Baixar o codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar o ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar ferramentas necessarias
        run: pip install google-genai pandas requests

      - name: Executar o script do Auditor IA
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python bot.py

      - name: Salvar planilha atualizada de volta no GitHub
        run: |
          git config --global user.name "Auditor Robot"
          git config --global user.email "bot@github.com"
          git add relatorio_diario_marica.csv
          git commit -m "Planilha updated pela IA [Automático]" || exit 0
          git push
